spring:
  application:
    name: chap06-spring-data-jpa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: ohgiraffers
  jpa:
    generate-ddl: true
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true